import { configureStore, createSlice } from '@reduxjs/toolkit'
//createSlice is a utility from Redux Toolkit that simplifies the process of creating reducers and actions

const initialState = {counter : 0, showCounter : true}
const counterSlice = createSlice({
    name: 'counter', //name of the slice
    initialState,   //initial state of the slice
    reducers: {
        //action creators are automatically generated by createSlice
        increment(state){
            state.counter++; //we can directly mutate the state here because of the immer library used by Redux Toolkit
        },
        decrement(state){
            state.counter--; //we can directly mutate the state here because of the immer library used by Redux Toolkit
        },
        increase(state, action){
            state.counter += action.amount
        },
        toggleCounter(state) {
            state.showCounter = !state.showCounter;
        }
        //no need to define action types, they are automatically generated
    }
});

const counterReducer = (state = initialState , action) => {
    if(action.type === 'increment') {
        return { 
            counter: state.counter + 1 ,
            showCounter:state.showCounter //showing the initial state of showCounter
        }
    }

    if(action.type === 'increase'){
        return{
            counter: state.counter + action.amount,
            showCounter:state.showCounter  //we always return a brand new object in redux, a snapshot of the state!

        }
    }
    
    if(action.type === 'decrement') {
        return { 
            counter: state.counter - 1,
            showCounter:state.showCounter //we always return a brand new object in redux, a snapshot of the state!
        }
    }

    if(action.type === 'toggler'){
        return{
            showCounter : !state.showCounter,
            counter: state.counter //keeping the counter value same
        }
    }

    return state;

}

//connect react app to redux store
const store = configureStore({
    reducer: counterSlice.reducer //using the reducer from the slice we created
})

export default store;